accounts/urls.py
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView, LogoutView

app_name = "accounts"

urlpatterns = [
    # url(r'^login/$', views.login, name='login'),
    url(
        r"^login/$",
        LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    url(r"^logout/$", LogoutView.as_view(), name="logout"),
    # url(r'^logout$', views.logout, name='logout'),
    # signup for externals
    url(
        r"^external/create_account$",
        views.external_create_account,
        name="external_create_account",
    ),
    # login for externals
    url(r"^external/login$", views.external_login, name="external_login"),
]

ais/local/urls.py
from ais.common.urls import *
from django.conf.urls import include, url
from kth_login import views as kth_login_views

urlpatterns += [
    url(r"^login/", kth_login_views.kth_login, name="login"),
    url(r"^oidc/kth/callback$", kth_login_views.authorize, name="authorize"),
]

api/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r"^$", views.root),
    url(r"^events/", include("events.api_urls")),
    url(r"^exhibitors/", include("exhibitors.api_urls")),
    url(r"^banquet/", include("banquet.api_urls")),
    url(r"^fair/", include("fair.api_urls")),
    url(r"^registration/", include("register.api_urls")),
    url(r"^accounting/", include("accounting.api_urls")),
    url(r"^catalogueselections/", views.catalogueselections),
    url(r"^news/", views.news),
    url(r"^organization/v2", views.organization_v2),
    url(r"^organization/", views.organization),
    url(r"^create_magic_link/", views.create_magic_link, name="create_magic_link"),
    url(r"^partners/", views.partners),
    url(r"^questions/?$", views.questions),
    url(r"^recruitment/$", views.recruitment),
    url(r"^recruitment_data/$", views.recruitment_data),
    url(r"^dates/$", views.dates),
    url(r"^student_profile$", views.student_profile),
    url(r"^matching/$", views.matching),
    url(r"^matching/choices$", views.matching_choices),
    url(r"^companies", views.companies),
]

companies/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^$", views.companies_list, name="companies_list"),
    url(r"^new$", views.companies_new, name="companies_new"),
    url(r"^slack_call$", views.companies_slack_call, name="companies_slack_call"),
    url(r"^statistics$", views.statistics, name="statistics"),
    url(r"^email$", views.email, name="email"),
    url(
        r"^send-order-summaries$",
        views.send_order_summaries,
        name="send_order_summaries",
    ),
    url(r"^groups$", views.groups, name="groups_list"),
    url(r"^groups/new$", views.groups, name="groups_new"),
    url(r"^groups/(?P<pk>\d+)$", views.groups, name="groups_edit"),
    url(r"^contracts/export$", views.contracts_export, name="contracts_export"),
    url(r"^(?P<pk>\d+)$", views.companies_view, name="companies_view"),
    url(r"^(?P<pk>\d+)/details$", views.companies_details, name="companies_details"),
    url(r"^(?P<pk>\d+)/edit$", views.companies_edit, name="companies_edit"),
    url(
        r"^(?P<pk>\d+)/edit/groups/(?P<group_pk>\d+)$",
        views.companies_edit,
        name="companies_edit_groups",
    ),
    url(
        r"^(?P<pk>\d+)/edit/responsibles/(?P<responsible_group_pk>\d+)$",
        views.companies_edit,
        name="companies_edit_responsibles_edit",
    ),
    url(
        r"^(?P<pk>\d+)/edit/responsibles/(?P<responsible_group_pk>\d+)/remove$",
        views.companies_edit_responsibles_remove,
        name="companies_edit_responsibles_remove",
    ),
    url(
        r"^(?P<pk>\d+)/orders/new$",
        views.companies_orders_new,
        name="companies_orders_new",
    ),
    url(
        r"^(?P<pk>\d+)/orders/(?P<order_pk>\d+)$",
        views.companies_orders_edit,
        name="companies_orders_edit",
    ),
    url(
        r"^(?P<pk>\d+)/orders/(?P<order_pk>\d+)/remove$",
        views.companies_orders_remove,
        name="companies_orders_remove",
    ),
    url(
        r"^(?P<pk>\d+)/comments/(?P<comment_pk>\d+)/edit$",
        views.companies_comments_edit,
        name="companies_comments_edit",
    ),
    url(
        r"^(?P<pk>\d+)/comments/(?P<comment_pk>\d+)/remove$",
        views.companies_comments_remove,
        name="companies_comments_remove",
    ),
    url(
        r"^(?P<pk>\d+)/contacts/(?P<contact_pk>\d+)/edit$",
        views.companies_contacts_edit,
        name="companies_contacts_edit",
    ),
]

register/urls.py
from re import template
from django.conf.urls import url
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import reverse_lazy
from . import views
from .forms import LoginForm, ResetPasswordForm, SetNewPasswordForm

app_name = "anmalan"

""" For virtual fair, remove following lines from urlpatterns below:
	url(r'^(?P<company_pk>[0-9]+)/transport$', views.transport, name = 'transport'),
	url(r'^(?P<company_pk>[0-9]+)/lunchtickets$', views.lunchtickets, name = 'lunchtickets'),
	url(r'^(?P<company_pk>[0-9]+)/lunchtickets/new$', views.lunchtickets_form, name = 'lunchtickets_new'),
	url(r'^(?P<company_pk>[0-9]+)/lunchtickets/(?P<lunch_ticket_pk>[0-9]+)$', views.lunchtickets_form, name = 'lunchtickets_edit'),
	url(r'^(?P<company_pk>[0-9]+)/banquet$', views.banquet, name = 'banquet'),
	url(r'^(?P<company_pk>[0-9]+)/banquet/new$', views.banquet_form, name = 'banquet_new'),
	url(r'^(?P<company_pk>[0-9]+)/banquet/(?P<banquet_participant_pk>[0-9]+)$', views.banquet_form, name = 'banquet_edit'),
"""

urlpatterns = [
    url(r"^$|^form(?:/.*)?$", views.choose_company, name="choose_company"),
    url(r"^(?P<company_pk>[0-9]+)/registration$", views.form, name="registration"),
    url(r"^(?P<company_pk>[0-9]+)/events$", views.events, name="events"),
    url(r"^user", views.create_user, name="create_user"),
    url(r"^password/change", views.change_password, name="change_password"),
    url(
        r"^login/$",
        LoginView.as_view(
            template_name="register/login.html", authentication_form=LoginForm
        ),
        name="login",
    ),
    url(r"^logout/$", LogoutView.as_view(), name="logout"),
    url(
        r"^password_reset/$",
        PasswordResetView.as_view(
            template_name="register/outside/reset_password.html",
            form_class=ResetPasswordForm,
            success_url=reverse_lazy("anmalan:password_reset_done"),
            email_template_name="register/outside/reset_password_email.html",
        ),
        name="password_reset",
    ),
    url(
        r"^password_reset/done/$",
        PasswordResetDoneView.as_view(
            template_name="register/outside/reset_password_done.html"
        ),
        name="password_reset_done",
    ),
    url(
        r"^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$",
        PasswordResetConfirmView.as_view(
            template_name="register/outside/reset_password_confirm.html",
            success_url=reverse_lazy("anmalan:password_reset_complete"),
            form_class=SetNewPasswordForm,
        ),
        name="password_reset_confirm",
    ),
    url(
        r"^reset/done/$",
        PasswordResetCompleteView.as_view(
            template_name="register/outside/reset_password_complete.html"
        ),
        name="password_reset_complete",
    ),
    url(r"^(?P<company_pk>[0-9]+)/transport$", views.transport, name="transport"),
    url(
        r"^(?P<company_pk>[0-9]+)/lunchtickets$",
        views.lunchtickets,
        name="lunchtickets",
    ),
    url(
        r"^(?P<company_pk>[0-9]+)/lunchtickets/new$",
        views.lunchtickets_form,
        name="lunchtickets_new",
    ),
    url(
        r"^(?P<company_pk>[0-9]+)/lunchtickets/(?P<lunch_ticket_pk>[0-9]+)$",
        views.lunchtickets_form,
        name="lunchtickets_edit",
    ),
    url(r"^(?P<company_pk>[0-9]+)/banquet$", views.banquet, name="banquet"),
    url(
        r"^(?P<company_pk>[0-9]+)/banquet/new$", views.banquet_form, name="banquet_new"
    ),
    url(
        r"^(?P<company_pk>[0-9]+)/banquet/(?P<banquet_participant_pk>[0-9]+)$",
        views.banquet_form,
        name="banquet_edit",
    ),
]

register/models.py
from django.db import models
from django.db.models import DEFERRED
from django.utils import timezone


# A 'Contact' is a person working for a 'Company'
class SignupContract(models.Model):
    name = models.CharField(max_length=30)
    contract = models.FileField(upload_to="contracts/%Y%m%d/")
    fair = models.ForeignKey("fair.Fair", on_delete=models.CASCADE)
    types = [("INITIAL", "Initial"), ("COMPLETE", "Complete")]
    type = models.CharField(
        max_length=200, choices=types, null=False, blank=False, default=types[0]
    )
    contract_company_type = models.ForeignKey(
        "companies.CompanyType", null=False, blank=False, on_delete=models.CASCADE
    )
    current = models.BooleanField(default=True)
    current.help_text = "Used to determine which contract for a fair, type and company type that should be used if several have been uploaded. Only one contract in this group can be marked as current."
    default = models.BooleanField(default=False)
    default.help_text = "Used to determine which contract for a fair and type that is the default one. Only one contract per fair and type can be marked as current, <strong>make sure one default contract exists before registration opens.</strong>."

    _loaded_values = None

    # These special overrides are meant to prevent anyone from changing an uploaded contract that some companies might already have agreed to
    @classmethod
    def from_db(cls, db, field_names, values):
        instance = super().from_db(db, field_names, values)
        instance._loaded_values = dict(zip(field_names, values))

        return instance

    def save(self, *args, **kwargs):
        if self._loaded_values:
            if (
                self.contract != self._loaded_values["contract"]
                or self.fair.id != self._loaded_values["fair_id"]
            ):
                raise ValueError(
                    "Not allowed to change contract, upload a new one instead!"
                )

        if self.current:
            # set all other contracts for this fair, type and contract_company_type to false to guarantee only one is current
            for contract in SignupContract.objects.filter(
                fair=self.fair,
                type=self.type,
                contract_company_type=self.contract_company_type,
                current=True,
            ):
                if contract != self:
                    contract.current = False
                    contract.save()

        if self.default:
            # set all other contracts for this fair and type to false to guarantee only one is default
            for contract in SignupContract.objects.filter(
                fair=self.fair, type=self.type, default=True
            ):
                if contract != self:
                    contract.default = False
                    contract.save()

        super(SignupContract, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class SignupLog(models.Model):
    contract = models.ForeignKey("SignupContract", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    company = models.ForeignKey(
        "companies.Company",
        null=True,
        on_delete=models.CASCADE,
        related_name="signature",
    )
    company_contact = models.ForeignKey(
        "companies.CompanyContact", on_delete=models.CASCADE, null=True, blank=True
    )
    ip_address = models.GenericIPAddressField(null=True, blank=True)

    types = [
        ("initial", "Initial"),
        ("complete", "Complete"),
    ]

    type = models.CharField(choices=types, null=True, blank=True, max_length=30)

    def get_company_contact_name(self):
        return (
            "-" if self.company_contact == None else self.company_contact.company.name
        )

    def __str__(self):
        return self.get_company_contact_name() + " for " + self.contract.name

    class Meta:
        ordering = [
            "-timestamp",
        ]

templates/register/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8"> {% include "header.html" %} {% block head-extra %}{% endblock %}
    <link href="{% static 'bootstrap.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'login-home.css' %}" rel="stylesheet" media="screen">
      <link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
</head>

<body>
{% block content %} {% endblock %}
</body>
</html>

templates/register/change_password.html
{% load staticfiles %}{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta charset="utf-8">
		{% include "header.html" %}{% block head-extra %}{% endblock %}
		<!--<link href="{% static 'registration_style.css' %}" rel="stylesheet" media="screen">-->
		<link href="{% static 'login-home.css' %}" rel="stylesheet" media="screen">
	</head>

	<body>
		<div class="container">
			<div class="headline">
				<svg class="armada-logo" viewBox="305 16 320 150" width="555px" height="250px" version="1.1">
					<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="250px" width="780px"/>
				</svg>
				<h2>Change Password</h2>
			</div>
			<div class="form-container">
				<form method="post">{% csrf_token %} {{ form | crispy }}
					<button type="submit" class="btn-green btn-signin">Save</button>
				</form>
				<a href="{% url 'anmalan:index' %}" class="forgot-password">Go back</a>
				<svg viewBox="50 90 200 200" width="100px" height="180px" version="1.1">
					<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
				</svg>
			</div>
		</div>
	</body>
</html>

templates/register/choose_company.html
{% load staticfiles %}<!DOCTYPE html>

<html lang="en">

<head>
	<title>THS Armada</title>
	<script src="{% static 'js/jquery.js' %}" charset="utf-8"></script>
	{% include "header.html" %} {% block head-extra %}{% endblock %}
	<link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
	<style type="text/css">
		#narrow_content
		{
			margin: 15px auto;
			padding: 10px 15px;
			max-width: 700px;
			background: #353535;
			border: 1px dotted #333333;
		}
	</style>
</head>

<body>
	<div id="narrow_content">
		{% if company_contacts %}
			<h1>Choose company</h1>
			<p>Your account is associated with multiple companies. Choose which one you would like to represent.</p>
			
			<ul>
				{% for company_contact in company_contacts %}
					<li><a href="{% url 'anmalan:registration' company_contact.company.pk %}">{{ company_contact.company.name }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<h1>No companies linked</h1>
			<p>Your account is not linked with any companies.</p>
		{% endif %}
	</div>
</body>

templates/register/company_form.html
{% load crispy_forms_tags %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta charset="utf-8">
		{% include "header.html" %}{% block head-extra %}{% endblock %}
		<link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
		<script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
	</head>

	<body>
		<div class="text-center container">
			<div class="row">
				<div class="headline">
					<svg class="armada-logo" viewBox="305 16 320 150" width="555px" height="250px" version="1.1">
						<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="250px" width="780px"/>
					</svg>
					<h2>Company profile</h2>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<form method="post">{% csrf_token %}
						<h3>Company info</h3>
						{{ form | crispy }}
						{% if contact_form %}
							<!-- This template is used both when editing just company information and when creating a new company which requires contact information as well. Therefore this other section is just displayed when contact information is requested. -->
							</br>
							<h3> Contact Person </h3>
							{{ contact_form | crispy }}
							{{ user_form | crispy }}
						{% endif %}
						<p align="left">* Required fields</p>
						<button type="submit" class="btn btn-green">Save</button>
					</form>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<svg viewBox="50 50 200 200" width="100px" height="100px" version="1.1">
						<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
					</svg>
				</div>
			</div>
		</div>
	</body>
</html>

templates/register/create_external_user.html
{% load crispy_forms_tags %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8"> {% include "header.html" %} {% block head-extra %}{% endblock %}
    <link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'login_style_additions.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
</head>

<body>
    <div class="container text-center">
      <div class="headline">
        <svg class="armada-logo" viewBox="305 16 320 150" width="555px" height="250px" version="1.1">
				   <image  xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="250px" width="780px"/>
        </svg>
        <h1 class="login-welcome">Welcome!</h1>
      </div>
        <div class="row header-row">
            <div class="col-md-6 col-md-offset-3">
                <p class="important-text">If you are a first time visitor or have forgotten your password <a href="{% url 'anmalan:password_reset' %}">click here</a></p>
                <p>If you already have an account. Please use one of the options below to log in;</p>
                <p>
                  <a href="/saml2/login"><img src="/static/images/kth_login_button.png" alt="Login with KTH"></a>
                </p>
                <p>
                  <a href="{% url 'anmalan:external_login' %}" class="btn btn-default btn-green"><span class="bigger-button">E-mail & Password Login</span></a>
                </p>
                <svg viewBox="50 90 200 200" width="100px" height="180px" version="1.1">
      				<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
            </svg>
            </div>
        </div>
        <!-- signup is closed
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <form method="post">
              {% csrf_token %}
              {{ form | crispy }}
              <button type="submit" class="btn btn-success">Submit</button>
            </form>
          </div>
        </div>
      -->
    </div>
</body>

</html>

templates/register/create_user.html
{% load crispy_forms_tags %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta charset="utf-8">
		{% include "header.html" %}{% block head-extra %}{% endblock %}
		<link href="{% static 'registration_style.css' %}" rel="stylesheet" media="screen">
		<script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
	</head>

	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					<img src="{% static 'images/armada_logo_text_left_black.svg' %}" alt="Armada Ship" class="main-logo-small">
				</div>
			</div>
		
			<div class="row header-row">
				<div class="col-md-12">
					<h1>Create a new account</h1>
				</div>
			</div>

			<div class="row">
				<div class="col-md-8">
					<a href="{% url 'anmalan:create_company' %}">
						<p>Not in the company list? Create a new company profile here!</p>
					</a>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<form method="post">
						{% csrf_token %} {{ contact_form | crispy }} {{ user_form | crispy }}
						<p align="left">* Required fields</p>
						<button type="submit" class="btn btn-success">Submit</button>
						<a href="{% url 'anmalan:index' %}"><button type="button" class="btn btn-default">Back</button></a>
					</form>
				</div>
			</div>
		</div>
	</body>
</html>

templates/register/home.html
{% load crispy_forms_tags %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8"> {% include "header.html" %} {% block head-extra %}{% endblock %}>
    <link href="{% static 'bootstrap.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'login-home.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1> Welcome to {{ fair }}! </h1>
             </div>
             <svg class="armada-ship-green" viewBox="50 90 200 200" width="100px" height="180px" version="1.1">
                  <image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
              </svg>

        </div>
        <div class="row header-row">
            <div class="col-md-12">
              <a href="{{contract_url}}">Read the contract</a>
                <p class="box-danger">The complete registration for {{ fair }} is open between <span class="text-danger">1st of July 00:01 and 4th of September 23:59</span>.</p>
            </div>
        </div>
        <div class="row">
            <p>Make sure the form is completed and sent in before the last date of registration. It is possible to start with the form, save it by clicking "Save" in the right bottom corner, and then continue later. The questions in the form are divided into 10 pages and you can fill out the information in any order you like. Questions marked with (*) are mandatory.</p>
            <p>Some information in this form may be copied from your profile. Please check this information so that it is updated for THS Armada 2017. Your registration is completed when you click on the button "Submit" in the right bottom corner. When you have submitted the application you will receive a confirmation e­mail as soon as the application has been approved.</p>
            <p class ="text-danger"> Please note that the complete registration is binding and you will be liable for all additional services chosen, provided that Armada is be able to supply your organisation with your choices.</p>
        </div>
        <div class="row spacer">
            <div class="col-md-12 mail-container">
              <div class="mail">
                <p class="mail-name">Lovisa Westerlund</p>
                <p class="mail-role">Project Manager</p>
                <a class = "mail-ref" href="mailto:armada@ths.kth.se">armada@ths.kth.se</a><br/>
                +46 70 790 98 44
              </div>
            </div>
        </div>
    </div>
      </body>

</html>

templates/register/index.html
{% load crispy_forms_tags %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8"> {% include "header.html" %} {% block head-extra %}{% endblock %}
    <link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
    <script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
</head>

<body>
    <div class="text-center container">
        <div class="row">
            <div class="headline">
                <svg class="armada-logo" viewBox="305 16 320 150" width="555px" height="250px" version="1.1">
                    <image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="250px" width="780px"/>
                </svg>
                <h2>Company registration for {{fair}} </h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="text-center form-container">
                    {% if timeFlag == 'warning' %}
                        <h4 class="text-danger"> The complete registration for THS Armada closes {{time_end }}. </h4>
                    {% elif timeFlag == 'closed' or timeFlag == 'overdue' %}
                        <h4 class="text-danger"> The complete registration for THS Armada closed on {{ time_end }}. </h4>
                    {% endif %}
                    <p> Sign in with existing account or create a new </p>
                    <a href="{% url 'anmalan:login' %}" class="btn-signin btn-green">Sign in</a>
                    <a href="{% url 'anmalan:create_company_user' %}" class="btn-signin btn-green">Create Account</a>
                    <div>
                        <svg viewBox="50 50 200 200" width="100px" height="100px" version="1.1">
                            <image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

templates/register/login.html
{% load crispy_forms_tags %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta charset="utf-8">
		{% include "header.html" %}{% block head-extra %}{% endblock %}
		<link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
		<script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
	</head>

	<body>
		<div class="text-center container">
			<div class="headline">
				<svg class="armada-logo" viewBox="305 16 320 150" width="555px" height="250px" version="1.1">
					<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="250px" width="780px"/>
				</svg>
				<h2>Company Sign in</h2>
			</div>

			<div class="form-container login-form">
				<p>Sign in with your credentials to access THS Armada.</p>
				<form method="post">
					{% csrf_token %} {{ form|crispy }}
					<input type="hidden" name="next" value='/register'/>
					<button class="btn-signin btn-green">Sign in</button>
				</form>
				<a href="{% url 'anmalan:password_reset' %}" class="forgot-password">Forgot password</a>
				<svg viewBox="50 90 200 200" width="100px" height="180px" version="1.1">
					<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
				</svg>
			</div>
		</div>
	</body>
</html>

templates/register/reset_password.html
{% load staticfiles %}{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<meta charset="utf-8">
		{% include "header.html" %}{% block head-extra %}{% endblock %}
		<link href="{% static 'complete_registration.css' %}" rel="stylesheet" media="screen">
		<link href="{% static 'login_style_additions.css' %}" rel="stylesheet" media="screen">
	</head>

	<body>
		<div class="container text-center">
			<div class="headline">
				<svg class="armada-logo" viewBox="305 16 320 150" width="555px" height="250px" version="1.1">
					<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="250px" width="780px"/>
				</svg>
				<h2>Reset password</h2>
			</div>

			<div class="form-container reset-password-form">
				<p class="">Enter your e-mail to set a new password.</p>
				<form method="post">{% csrf_token %} {{ form | crispy }}
					<button type="submit" class="btn-green btn-signin">Send</button>
				</form>

				<a href="{% url 'anmalan:index' %}" class="forgot-password">Go back</a>

				<svg viewBox="50 90 200 200" width="100px" height="180px" version="1.1">
					<image xlink:href="{% static 'images/armada_logo_text_left_green.svg' %}" alt="Armada" height="300px" width="700px"/>
				</svg>
			</div>
		</div>
	</body>
</html>