ais/common/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from ais.common import settings
from django.conf.urls.static import static
from fair.views import login_redirect
from testpage.views import testpage
from exhibitors.views import UserAutocomplete
from magic_link import urls as magic_link_urls

urlpatterns = [
    url(r"^accounts/", include("accounts.urls")),
    url(r"^admin/", admin.site.urls),
    url(r"^companies/", include("companies.urls")),
    url(r"^register/", include("register.urls")),
    url(r"^api/", include("api.urls")),
    url(r"^banquet/", include("banquet.urls")),
    url(r"^$", login_redirect),
    url(r"^fairs/", include("urls.urls")),
    url(r"^journal/", include("journal.urls")),
    url(r"^banquet/", include("banquet.urls_external")),
    url(r"^unirel/", include("unirel.urls_external")),
    url(r"^", include("fair.urls_external")),
    url(r"^testpage/", include("testpage.urls")),
    url(r"^payments/", include("payments.urls")),
    url(r"^hijack/", include("hijack.urls")),
    url(r"^magic_link/", include(magic_link_urls)),
    url(
        r"^user-autocomplete/$",
        UserAutocomplete.as_view(),
        name="user-autocomplete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = "AIS administration"
admin.site.site_header = "AIS administration"
admin.site.index_title = "AIS administration"

ais/local/urls.py
from ais.common.urls import *
from django.conf.urls import include, url
from kth_login import views as kth_login_views

urlpatterns += [
    url(r"^login/", kth_login_views.kth_login, name="login"),
    url(r"^oidc/kth/callback$", kth_login_views.authorize, name="authorize"),
]

api/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r"^$", views.root),
    url(r"^events/", include("events.api_urls")),
    url(r"^exhibitors/", include("exhibitors.api_urls")),
    url(r"^banquet/", include("banquet.api_urls")),
    url(r"^fair/", include("fair.api_urls")),
    url(r"^registration/", include("register.api_urls")),
    url(r"^accounting/", include("accounting.api_urls")),
    url(r"^catalogueselections/", views.catalogueselections),
    url(r"^news/", views.news),
    url(r"^organization/v2", views.organization_v2),
    url(r"^organization/", views.organization),
    url(r"^create_magic_link/", views.create_magic_link, name="create_magic_link"),
    url(r"^partners/", views.partners),
    url(r"^questions/?$", views.questions),
    url(r"^recruitment/$", views.recruitment),
    url(r"^recruitment_data/$", views.recruitment_data),
    url(r"^dates/$", views.dates),
    url(r"^student_profile$", views.student_profile),
    url(r"^matching/$", views.matching),
    url(r"^matching/choices$", views.matching_choices),
    url(r"^companies", views.companies),
]

fair/urls.py
from django.conf.urls import url

from . import views

app_name = "fair"

urlpatterns = [
    url(r"^$", views.index, name="home"),
    url(r"^tickets$", views.tickets, name="tickets"),
    url(r"^check_in$", views.lunchtickets_check_in, name="lunchtickets_check_in"),
    url(r"^lunchtickets$", views.lunchtickets, name="lunchtickets"),
    url(r"^lunchtickets/create$", views.lunchticket_create, name="lunchticket_create"),
    url(
        r"^lunchtickets/(?P<token>[A-Za-z0-9]+)$", views.lunchticket, name="lunchticket"
    ),
    url(
        r"^lunchtickets/(?P<token>[A-Za-z0-9]+)/remove$",
        views.lunchticket_remove,
        name="lunchticket_remove",
    ),
    url(
        r"^lunchtickets/(?P<token>[A-Za-z0-9]+)/send$",
        views.lunchticket_send,
        name="lunchticket_send",
    ),
]

people/urls.py
from django.conf.urls import url
from . import views

app_name = "people"

urlpatterns = [
    url(r"^$", views.list, name="list"),
    url(r"^edit$", views.edit, name="edit"),
    url(r"^(?P<pk>\d+)$", views.profile, name="profile"),
    url(r"^profile_delete/(?P<pk>\d+)$", views.profile_delete, name="profile_delete"),
]

fair/views.py
import json

from django.contrib.auth.decorators import permission_required
from django.db.models import Count
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy
from django.utils import timezone

from banquet.models import Participant, Banquet
from companies.models import CompanyContact
from events.models import Event
from fair import serializers
from recruitment.models import RecruitmentApplication
from recruitment.models import RecruitmentPeriod, Role

from .forms import LunchTicketForm, LunchTicketSearchForm
from .models import Fair, LunchTicket, LunchTicketSend
from .models import FairDay, OrganizationGroup


def login_redirect(request):
    next = request.GET.get("next")
    if next and next[-1] == "/":
        next = next[:-1]

    print(request.user)
    if request.user.is_authenticated:
        contact = CompanyContact.objects.filter(user=request.user).first()
        fair = Fair.objects.filter(current=True).first()
        if fair is None:
            fair = Fair.objects.filter.first()
        year = fair.year

        if contact is not None:
            return redirect("anmalan:choose_company")

        return redirect("fair:home", year)

    return render(request, "login.html", {"next": next})


def index(request, year=None):
    fair = Fair.objects.filter(year=year).first()
    if fair is None:
        fair = Fair.objects.filter(current=True).first()
        return redirect("fair:home", fair.year)

    if not request.user.is_authenticated:
        return render(request, "login.html", {"next": next, "fair": fair})

    if request.user.has_perm("events.base"):
        events = Event.objects.filter(fair=fair).annotate(
            num_participants=Count("participant")
        )
    else:
        events = Event.objects.filter(fair=fair, published=True)

    recruitment_period = RecruitmentPeriod.objects.filter(fair=fair).order_by(
        "-start_date"
    )

    return render(
        request,
        "fair/home.html",
        {
            "recruitment": {
                "recruitment_periods": recruitment_period,
            },
            "events": events,
            "fair": fair,
        },
    )


@permission_required("fair.lunchtickets")
def lunchtickets(request, year):
    fair = get_object_or_404(Fair, year=year)

    form = LunchTicketSearchForm(request.POST or None)

    form.fields["days"].queryset = FairDay.objects.filter(fair=fair)

    if request.POST and form.is_valid():
        lunchtickets = (
            LunchTicket.objects.select_related("user")
            .select_related("company")
            .select_related("day")
            .select_related("time")
            .prefetch_related("dietary_restrictions")
            .filter(fair=fair)
        )
        lunchtickets_filtered = []

        for lunchticket in lunchtickets:
            if len(form.cleaned_data["used_statuses"]) > 0:
                found = False

                for s in form.cleaned_data["used_statuses"]:
                    if s == "USED" and lunchticket.used:
                        found = True
                        break

                    if s == "NOT_USED" and not lunchticket.used:
                        found = True
                        break

                if not found:
                    continue

            if len(form.cleaned_data["types"]) > 0:
                found = False

                for t in form.cleaned_data["types"]:
                    if t == "STUDENT" and lunchticket.company is None:
                        found = True
                        break

                    if t == "COMPANY" and lunchticket.company is not None:
                        found = True
                        break

                if not found:
                    continue

            if len(form.cleaned_data["sent_statuses"]) > 0:
                found = False

                for t in form.cleaned_data["sent_statuses"]:
                    if t == "SENT" and lunchticket.sent:
                        found = True
                        break

                    if t == "NOT_SENT" and not lunchticket.sent:
                        found = True
                        break

                if not found:
                    continue

            if len(form.cleaned_data["days"]) > 0:
                found = False

                for d in form.cleaned_data["days"]:
                    if lunchticket.day == d:
                        found = True
                        break

                if not found:
                    continue

            lunchtickets_filtered.append({"t": lunchticket, "drl": []})

        dietary_restrictions_all = {}

        if form.cleaned_data["include_dietary_restrictions"]:
            for lunchticket in lunchtickets_filtered:
                for dietary_restriction in lunchticket["t"].dietary_restrictions.all():
                    if dietary_restriction in dietary_restrictions_all:
                        dietary_restrictions_all[dietary_restriction] += 1
                    else:
                        dietary_restrictions_all[dietary_restriction] = 1

            for lunchticket in lunchtickets_filtered:
                lunchticket["drl"] = [
                    True
                    if dietary_restriction
                    in lunchticket["t"].dietary_restrictions.all()
                    else False
                    for dietary_restriction in dietary_restrictions_all
                ]

    else:
        lunchtickets_filtered = []
        dietary_restrictions_all = {}

    return render(
        request,
        "fair/lunchtickets.html",
        {
            "fair": fair,
            "my_lunchtickets": LunchTicket.objects.filter(fair=fair, user=request.user),
            "form": form,
            "has_searched": request.POST and form.is_valid(),
            "lunchtickets": lunchtickets_filtered,
            "dietary_restrictions": [
                {"name": x, "count": dietary_restrictions_all[x]}
                for x in dietary_restrictions_all
            ],
        },
    )


@permission_required("fair.lunchtickets")
def lunchticket(request, year, token):
    fair = get_object_or_404(Fair, year=year)
    lunch_ticket = get_object_or_404(LunchTicket, fair=fair, token=token)

    if request.user != lunch_ticket.user and not request.user.has_perm(
        "fair.lunchtickets"
    ):
        return HttpResponseForbidden()

    if request.user.has_perm("fair.lunchtickets"):
        form = LunchTicketForm(request.POST or None, instance=lunch_ticket)

        if request.POST and form.is_valid():
            form.save()

    else:
        form = None

    return render(
        request,
        "fair/lunchticket.html",
        {
            "fair": fair,
            "lunch_ticket": lunch_ticket,
            "form": form,
            "sends": LunchTicketSend.objects.filter(lunch_ticket=lunch_ticket),
        },
    )


@permission_required("fair.lunchtickets")
def lunchticket_remove(request, year, token):
    fair = get_object_or_404(Fair, year=year)
    lunch_ticket = get_object_or_404(LunchTicket, fair=fair, token=token)

    lunch_ticket.delete()

    return redirect("fair:lunchtickets", fair.year)


@permission_required("fair.lunchtickets")
def lunchticket_send(request, year, token):
    fair = get_object_or_404(Fair, year=year)
    lunch_ticket = get_object_or_404(LunchTicket, fair=fair, token=token)

    eat_by = str(lunch_ticket.time) if lunch_ticket.time else str(lunch_ticket.day)
    email_address = (
        lunch_ticket.user.email if lunch_ticket.user else lunch_ticket.email_address
    )

    send_mail(
        "Lunch ticket " + eat_by,
        "Open the link below to redeem your lunch ticket at "
        + lunch_ticket.fair.name
        + ".\n\nDate: "
        + eat_by
        + "\n"
        + request.build_absolute_uri(
            reverse("lunchticket_display", args=[lunch_ticket.token])
        ),
        "noreply@armada.nu",
        [email_address],
        fail_silently=True,
    )

    LunchTicketSend(
        lunch_ticket=lunch_ticket, user=request.user, email_address=email_address
    ).save()

    lunch_ticket.sent = True
    lunch_ticket.save()

    return redirect("fair:lunchticket", fair.year, lunch_ticket.token)


@permission_required("fair.lunchtickets")
def lunchticket_create(request, year):
    fair = get_object_or_404(Fair, year=year)

    form = LunchTicketForm(request.POST or None, initial={"fair": fair})

    users = []

    for organization_group in OrganizationGroup.objects.filter(fair=fair):
        this_users_flat = [
            application.user
            for application in RecruitmentApplication.objects.select_related("user")
            .filter(
                delegated_role__organization_group=organization_group,
                status="accepted",
                recruitment_period__fair=fair,
            )
            .order_by("user__first_name", "user__last_name")
        ]
        users.append(
            [
                organization_group.name,
                [(user.pk, user.get_full_name()) for user in this_users_flat],
            ]
        )

    form.fields["user"].choices = [("", "---------")] + users

    if request.POST and form.is_valid():
        form.instance.fair = fair
        lunch_ticket = form.save()
        return redirect("fair:lunchticket", fair.year, lunch_ticket.token)

    return render(request, "fair/lunchticket_create.html", {"fair": fair, "form": form})


@permission_required("fair.lunchtickets")
def lunchtickets_check_in(request, year):
    fair = get_object_or_404(Fair, year=year)

    react_props = {}

    return render(
        request,
        "fair/lunch_ticket_check_in.html",
        {"react_props": json.dumps(react_props)},
    )


def lunchticket_display(request, token):

templates/fair/home.html
{% extends "base.html" %}
{% block content %}

  <img src="/static/images/armada_navigating_2019.png" class="home-image">

  <div class="row">
    <div class="col-md-12">

      <h2>Events</h2>
      {% include 'events/event_table.html' with events=events %}

      <h2>Recruitment</h2>
      <div class="table-responsive">
        <table class="table">
          <thead>
          <tr>
            <th class="col-md-4">Name</th>
            <th class="col-md-2">Date</th>
            {% if perms.recruitment.view_recruitment_applications %}
              <th class="col-md-4">Applications</th>
            {% else %}
              <th class="col-md-4"></th>
            {% endif %}
            <th class="col-md-2">Status</th>
          </tr>
          </thead>
          <tbody>
          {% for period in recruitment.recruitment_periods %}
            <tr>
              <td class="col-md-4"><a href="{% url 'recruitment_period' fair.year period.id %}">{{ period.name }}</a></td>
              <td class="col-md-2">{{ period.start_date|date:"d M" }} - {{ period.end_date|date:"d M" }}</td>
              {% if perms.recruitment.view_recruitment_applications %}
                <td class="col-md-4">{{ period.recruitmentapplication_set.count }}</td>
              {% else %}
                <td class="col-md-4"></td>
              {% endif %}
              <td class="col-md-2">
                {% if period.is_past %}
                  <span class="label label-default">Closed</span>
                {% elif period.is_future %}
                  <span class="label label-default">Not opened yet</span>
                {% else %}
                  <span class="label label-success">Open</span>
                {% endif %}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td>No recruitment period for the moment.</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

{% endblock %}

templates/fair/lunch_ticket_check_in.html
{% load render_bundle from webpack_loader %}
<title>THS Armada - Lunch Tickets</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"/>
<meta name="theme-color" content="#01d690">

<script>
  window.reactProps = {{ react_props|safe }};
</script>
<div id="react"></div>

{% render_bundle 'lunch_tickets_check_in' %}

templates/fair/lunchticket.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block nav-lunchtickets %}
	<li role="presentation" class="active"><a href="{% url 'fair:lunchtickets' fair.year %}">Lunch tickets</a></li>
{% endblock %}

{% block content %}
	<h1>Send over e-mail</h1>
	{% if sends %}
		<ul>
			{% for send in sends %}
				<li>Sent on {{ send.timestamp }} to <a href="mailto:{{ send.email_address }}">{{ send.email_address }}</a> by <a href="{{ send.user.pk }}">{{ send.user }}</a>.</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>This lunch ticket has never been sent out via e-mail.</p>
	{% endif %}
	
	<a href="{% url 'fair:lunchticket_send' fair.year lunch_ticket.token %}" class="btn btn-primary">Send ticket to {% if lunch_ticket.user %} {{ lunch_ticket.user.email }} {% else %} {{ lunch_ticket.email_address }} {% endif %}</a>
	
	<h1>Manage lunch ticket</h1>
	<form method="post">
		{% csrf_token %}
		{{ form | crispy }}
		<input type="submit" class="btn btn-primary" value="Save changes" />
		<a href="{% url 'fair:lunchticket_remove' fair.year lunch_ticket.token %}" class="btn btn-danger pull-right" onclick="return confirm('Confirm the removal.');">Delete lunch ticket</a>
	</form>
{% endblock %}

templates/fair/lunchticket_create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block nav-lunchtickets %}
	<li role="presentation" class="active"><a href="{% url 'fair:lunchtickets' fair.year %}">Lunch tickets</a></li>
{% endblock %}

{% block content %}
	<h1>Create lunch ticket</h1>
		
	<form method="post">
		{% csrf_token %}
		{{ form | crispy }}
		<input type="submit" class="btn btn-primary" value="Create lunch ticket" />
	</form>
{% endblock %}

templates/fair/lunchticket_display.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
		<meta charset="utf-8" />
		{% include "header.html" %}{% block head-extra %}{% endblock %}
		<link href="{% static 'registration_style.css' %}" rel="stylesheet" media="screen" />
		<script src="{% static 'js/setmobile.js' %}" type="text/javascript" charset="utf-8" async defer></script>
	</head>

	<body>
		<div class="container" style="max-width: 700px;">
			<div class="text-center headline">
				<h2>{{ lunch_ticket.fair }}</h2>
				<h1>Lunch ticket</h1>
			</div>

			<p><span style="font-weight: bold;">Date:</span> {% if lunch_ticket.time %} {{ lunch_ticket.time }} {% else %} {{ lunch_ticket.day }} {% endif %}</p>

			<p><span style="font-weight: bold;">Ticket originally sent to:</span><br />{% if lunch_ticket.email_address %} {{ lunch_ticket.email_address }} {% else %} {{ lunch_ticket.user.email }}{% endif %}</p>

			<p><span style="font-weight: bold;">Comment:</span><br />{% if lunch_ticket.comment %}{{ lunch_ticket.comment }}{% else %}<span style="font-style: italic;">(no comment)</span>{% endif %}</p>

			<p><span style="font-weight: bold;">Dietary restrictions:</span><br />
				{% if lunch_ticket.dietary_restrictions.all or lunch_ticket.other_dietary_restrictions %}
					{% if lunch_ticket.dietary_restrictions.all %}
						{{ lunch_ticket.dietary_restrictions.all | join:', ' }}
						{% if lunch_ticket.other_dietary_restrictions %}
							, {{ lunch_ticket.other_dietary_restrictions }}
						{% endif %}
					{% else %}
						{{ lunch_ticket.other_dietary_restrictions }}
					{% endif %}
				{% else %}
					<span style="font-style: italic;">(no dietary restrictions)</span>
				{% endif %}
			</p>
			<p>Please notify the restaurant about any dietary restrictions stated above.</p>

			{% if lunch_ticket.used %}
				<p class="text-danger">This lunch ticket has already been used.</p>
			{% else %}
				<div id="qrcode" style="margin: 50px auto 50px; max-width: 256px;"></div>

				<h4 style="font-size: 25pt; text-align: center;">{% if lunch_ticket.company %} {{ lunch_ticket.company }} {% endif %}</h4>

				<script src="//static.kottnet.net/javascript/qrcode.min.js"></script>
				<script>
					new QRCode(document.getElementById('qrcode'), '{{ lunch_ticket.token }}');
				</script>
			{% endif %}
		</div>
	</body>
</html>

templates/fair/lunchtickets.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block nav-lunchtickets %}
  <li role="presentation" class="active"><a href="{% url 'fair:lunchtickets' fair.year %}">Lunch tickets</a></li>
{% endblock %}

{% block content %}
  <div class="pull-right">
    <a href="{% url 'fair:lunchtickets_check_in' fair.year %}" class="btn btn-default">Check in</a>
    <a href="{% url 'fair:lunchticket_create' fair.year %}" class="btn btn-primary">Create lunch ticket</a>
  </div>
  <h1>Manage lunch tickets {% if has_searched %} ({{ lunchtickets | length }}){% endif %}</h1>

  <style type="text/css">
    .form_no_ul ul {
      margin: 0;
      padding: 0;
      margin: 0 0 20px 15px;
    }

    .form_no_ul ul li {
      list-style-type: none;
    }

    .form_no_ul ul li label {
      font-weight: 400;
    }
  </style>

  <form method="post" class="form_no_ul" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row">
      <div class="col-md-6">
        <label for="{{ form.used_statuses.id_for_label }}">{{ form.used_statuses.label }}</label>
        {{ form.used_statuses }}
        
        <label for="{{ form.sent_statuses.id_for_label }}">{{ form.sent_statuses.label }}</label>
        {{ form.sent_statuses }}
      </div>

      <div class="col-md-6">
        <label for="{{ form.types.id_for_label }}">{{ form.types.label }}</label>
        {{ form.types }}
        
        <label for="{{ form.days.id_for_label }}">{{ form.days.label }}</label>
        {{ form.days }}

        {{ form.include_dietary_restrictions }} <label
          for="{{ form.include_dietary_restrictions.id_for_label }}">{{ form.include_dietary_restrictions.label }}</label>
      </div>
    </div>

    <input class="btn btn-primary" type="submit" value="Refine search"/>
  </form>

  {% if has_searched %}
    <div class="table-responsive">
      <table class="table" id="lunchticket_table">
        <thead>
        <tr>
          <th>Used?</th>
          <th>Sent?</th>
          <th>Type</th>
          <th style="white-space: nowrap;">Date and time</th>
          <th>Name</th>
          <th>E-mail address</th>
          <th>Comment</th>
          <th>Other dietary restrictions</th>
          {% for dietary_restriction in dietary_restrictions %}
            <th style="white-space: nowrap;">{{ dietary_restriction.name }} ({{ dietary_restriction.count }})</th>
          {% endfor %}
        </tr>
        </thead>

        <tbody>
        {% for l in lunchtickets %}
          <tr>
            {% if l.t.used %}
              <td class="bg-success">Yes</td>
            {% else %}
              <td class="bg-danger">No</td>{% endif %}
            {% if l.t.sent %} <td class="bg-success">Yes</td>
            {% else %} <td class="bg-danger">No</td> {% endif %}
            <td>
              {% if l.t.user %} Student
              {% else %} Company {% endif %}
            </td>
            <td style="white-space: nowrap;">
              <a href="{% url 'fair:lunchticket' fair.year l.t.token %}">
                {% if l.t.time %} {{ l.t.time }}
                {% else %} {{ l.t.day }} {% endif %}
              </a>
            </td>
            <td style="white-space: nowrap;">
              {% if l.t.user %} <a href="{% url 'people:profile' fair.year l.t.user.pk %}">{{ l.t.user.get_full_name }}</a>
              {% else %} {{ l.t.company.name }} {% endif %}
            </td>
            <td>
              {% if l.t.user %} <a href="mailto:{{ l.t.user.email }}">{{ l.t.user.email }}</a>
              {% else %} <a href="mailto:{{ l.t.email_address }}">{{ l.t.email_address }}</a> {% endif %}
            </td>
            <td>{% if l.t.comment %} {{ l.t.comment }} {% endif %}
            <td>
              {% if l.t.other_dietary_restrictions %} {{ l.t.other_dietary_restrictions }} {% endif %}
            </td>
              {% for d in l.drl %}
                {% if d %}
                  <td style="text-align: center;" class="bg-danger">yes</td>
                {% else %}
                  <td style="text-align: center;">no</td>{% endif %}
              {% endfor %}
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
{% endblock %}

{% block scripts %}
  <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
  <link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
  <script>
    $(function () {
      $('#lunchticket_table').DataTable({'paging': false});
    })
  </script>
{% endblock %}

templates/fair/tickets.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}

{% block nav-tickets %}
  <li role="presentation" class="active"><a href="{% url 'fair:tickets' fair.year %}">Tickets</a></li>
{% endblock %}

{% block content %}
  <style>
    html {
      font-size: 16px;
    }
  </style>
  <div id="react"></div>
  <script>
    window.reactProps = {{ react_props|safe }};
  </script>
{% endblock %}

{% block scripts %}
  {% render_bundle 'tickets' %}
{% endblock scripts %}