ais/local/urls.py
from ais.common.urls import *
from django.conf.urls import include, url
from kth_login import views as kth_login_views

urlpatterns += [
    url(r"^login/", kth_login_views.kth_login, name="login"),
    url(r"^oidc/kth/callback$", kth_login_views.authorize, name="authorize"),
]

api/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r"^$", views.root),
    url(r"^events/", include("events.api_urls")),
    url(r"^exhibitors/", include("exhibitors.api_urls")),
    url(r"^banquet/", include("banquet.api_urls")),
    url(r"^fair/", include("fair.api_urls")),
    url(r"^registration/", include("register.api_urls")),
    url(r"^accounting/", include("accounting.api_urls")),
    url(r"^catalogueselections/", views.catalogueselections),
    url(r"^news/", views.news),
    url(r"^organization/v2", views.organization_v2),
    url(r"^organization/", views.organization),
    url(r"^create_magic_link/", views.create_magic_link, name="create_magic_link"),
    url(r"^partners/", views.partners),
    url(r"^questions/?$", views.questions),
    url(r"^recruitment/$", views.recruitment),
    url(r"^recruitment_data/$", views.recruitment_data),
    url(r"^dates/$", views.dates),
    url(r"^student_profile$", views.student_profile),
    url(r"^matching/$", views.matching),
    url(r"^matching/choices$", views.matching_choices),
    url(r"^companies", views.companies),
]

exhibitors/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.exhibitors, name="exhibitors"),
    url(r"^(?P<pk>\d+)$", views.exhibitor, name="exhibitor"),
    url(
        r"^(?P<pk>\d+)/transport$",
        views.exhibitor_transport,
        name="exhibitor_transport",
    ),
    url(r"^(?P<pk>\d+)/details$", views.exhibitor_details, name="exhibitor_details"),
    url(
        r"^(?P<pk>\d+)/coordinates$",
        views.exhibitor_coordinates,
        name="exhibitor_coordinates",
    ),
    url(
        r"^(?P<pk>\d+)/fair_location$",
        views.exhibitor_fair_location,
        name="exhibitor_fair_location",
    ),
    url(
        r"^(?P<pk>\d+)/contact_persons$",
        views.exhibitor_contact_persons,
        name="exhibitor_contact_persons",
    ),
    url(r"^(?P<pk>\d+)/check_in$", views.exhibitor_check_in, name="exhibitor_check_in"),
    url(
        r"^(?P<pk>\d+)/check_in/revert$",
        views.exhibitor_check_in_revert,
        name="exhibitor_check_in_revert",
    ),
    url(
        r"^(?P<pk>\d+)/comments/(?P<comment_pk>\d+)/edit$",
        views.exhibitor_comment_edit,
        name="exhibitor_comment_edit",
    ),
    url(
        r"^(?P<pk>\d+)/comments/(?P<comment_pk>\d+)/remove$",
        views.exhibitor_comment_remove,
        name="exhibitor_comment_remove",
    ),
    url(r"^view$", views.edit_view, name="edit_view"),
    url(r"^create$", views.create, name="create"),
    url(r"^export$", views.export, name="export"),
    url(
        r"^people_count/(?P<location_pk>[0-9]+)$",
        views.people_count,
        name="people_count",
    ),
    url(r"^booths$", views.booths, name="booths"),
    url(r"^booths/(?P<booth_pk>[0-9]+)$", views.booth, name="booth"),
    url(
        r"^booths/(?P<booth_pk>[0-9]+)/add$",
        views.exhibitor_in_booth_form,
        name="exhibitor_in_booth_add",
    ),
    url(
        r"^booths/(?P<booth_pk>[0-9]+)/(?P<exhibitor_pk>[0-9]+)$",
        views.exhibitor_in_booth_form,
        name="exhibitor_in_booth_edit",
    ),
    url(
        r"^booths/(?P<booth_pk>[0-9]+)/(?P<exhibitor_pk>[0-9]+)/remove$",
        views.exhibitor_in_booth_remove,
        name="exhibitor_in_booth_remove",
    ),
    url(r"^booth_placement$", views.booth_placement, name="booth_placement"),
]

orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    #   url(r'^$', views.products, name='products'),
    #   url(r'^(?P<pk>\d+)$', views.product, name='product'),
]

people/urls.py
from django.conf.urls import url
from . import views

app_name = "people"

urlpatterns = [
    url(r"^$", views.list, name="list"),
    url(r"^edit$", views.edit, name="edit"),
    url(r"^(?P<pk>\d+)$", views.profile, name="profile"),
    url(r"^profile_delete/(?P<pk>\d+)$", views.profile_delete, name="profile_delete"),
]

exhibitors/models.py
from django.db import models
from django.forms import ValidationError
from lib.image import UploadToDirUUID
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.utils.crypto import get_random_string

from accounting.models import Order
from banquet.models import Banquet, Participant
from recruitment.models import RecruitmentApplication
from fair.models import Fair, FairDay
from people.models import DietaryRestriction
from django.contrib.postgres.fields import JSONField


def get_random_32_length_string():
    return get_random_string(32)


class CatalogueIndustry(models.Model):
    industry = models.CharField(blank=False, max_length=255)
    category = models.ForeignKey(
        "CatalogueCategory", blank=True, null=True, on_delete=models.CASCADE
    )
    include_in_form = models.BooleanField(default=True)
    include_in_form.help_text = (
        "The alternative is only visible in forms if this attribute is checked."
    )

    def __str__(self):
        return self.industry

    class Meta:
        verbose_name_plural = "Catalogue industries"
        default_permissions = []
        ordering = ["category", "industry"]


class CatalogueValue(models.Model):
    value = models.CharField(blank=False, max_length=255)
    include_in_form = models.BooleanField(default=True)
    include_in_form.help_text = (
        "The alternative is only visible in forms if this attribute is checked."
    )

    def __str__(self):
        return self.value

    class Meta:
        default_permissions = []
        ordering = ["value"]


class CatalogueEmployment(models.Model):
    employment = models.CharField(blank=False, max_length=255)
    include_in_form = models.BooleanField(default=True)
    include_in_form.help_text = (
        "The alternative is only visible in forms if this attribute is checked."
    )

    def __str__(self):
        return self.employment

    class Meta:
        default_permissions = []
        ordering = ["employment"]


class CatalogueLocation(models.Model):
    location = models.CharField(blank=False, max_length=255)
    include_in_form = models.BooleanField(default=True)
    include_in_form.help_text = (
        "The alternative is only visible in forms if this attribute is checked."
    )

    def __str__(self):
        return self.location

    class Meta:
        default_permissions = []
        ordering = ["location"]


class CatalogueBenefit(models.Model):
    benefit = models.CharField(blank=False, max_length=255)
    include_in_form = models.BooleanField(default=True)
    include_in_form.help_text = (
        "The alternative is only visible in forms if this attribute is checked."
    )

    def __str__(self):
        return self.benefit

    class Meta:
        default_permissions = []
        ordering = ["benefit"]


class CatalogueCompetence(models.Model):
    competence = models.CharField(blank=False, max_length=255)
    category = models.ForeignKey(
        "CatalogueCategory", blank=True, null=True, on_delete=models.CASCADE
    )
    include_in_form = models.BooleanField(default=True)
    include_in_form.help_text = (
        "The alternative is only visible in forms if this attribute is checked."
    )

    def __str__(self):
        return self.competence

    class Meta:
        default_permissions = []
        ordering = ["category", "competence"]


class CatalogueCategory(models.Model):
    category = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.category

    class Meta:
        verbose_name_plural = "Catalogue categories"
        default_permissions = []
        ordering = ["category"]


class Location(models.Model):
    fair = models.ForeignKey(Fair, on_delete=models.CASCADE)
    parent = models.ForeignKey(
        "exhibitors.Location", on_delete=models.CASCADE, null=True, blank=True
    )
    name = models.CharField(blank=False, null=False, max_length=255)
    background = models.ImageField(
        upload_to=UploadToDirUUID("locations"), null=True, blank=True
    )
    people_count_enabled = models.BooleanField(default=False)
    people_count = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ["fair", "parent__name", "name"]
        unique_together = [["fair", "name"]]

    def __str__(self):
        return ((str(self.parent) + " -> ") if self.parent else "") + self.name


# A company (or organisation) participating in a fair
class Exhibitor(models.Model):
    company = models.ForeignKey("companies.Company", on_delete=models.CASCADE)
    fair = models.ForeignKey("fair.Fair", on_delete=models.CASCADE)
    contact_persons = models.ManyToManyField(User, blank=True)
    contact = models.ForeignKey(
        "companies.CompanyContact", null=True, blank=True, on_delete=models.CASCADE
    )
    tier = models.CharField(
        blank=True,
        null=True,
        max_length=255,
        choices=[
            ("1", "Bronze"),
            ("2", "Silver"),
            ("3", "Gold"),
        ],
    )
    booth_height = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Height of the booth (cm)"
    )
    electricity_total_power = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Estimated power consumption (W)"
    )
    electricity_socket_count = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Number of sockets"
    )
    electricity_equipment = models.TextField(
        blank=True, null=True, verbose_name="Description of equipment"
    )
    check_in_timestamp = models.DateTimeField(blank=True, null=True)
    check_in_comment = models.TextField(blank=True, null=True)
    check_in_user = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name="check_in_user",
        on_delete=models.SET_NULL,
    )
    catalogue_about = models.TextField(blank=True, null=True, max_length=600)
    catalogue_purpose = models.TextField(blank=True, null=True, max_length=600)
    catalogue_logo_squared = models.ImageField(
        upload_to=UploadToDirUUID("exhibitors", "catalogue_logo_squared"), blank=True
    )
    catalogue_logo_freesize = models.ImageField(
        upload_to=UploadToDirUUID("exhibitors", "catalogue_logo_freesize"), blank=True
    )
    catalogue_contact_name = models.CharField(
        blank=True, null=True, max_length=255, verbose_name="Contact person's name"
    )
    catalogue_contact_email_address = models.EmailField(
        blank=True,
        null=True,
        max_length=255,
        verbose_name="Contact person's e-mail address",
    )
    catalogue_contact_phone_number = models.CharField(
        blank=True,
        null=True,
        max_length=255,
        verbose_name="Contact person's phone number",
    )
    catalogue_industries = models.ManyToManyField(CatalogueIndustry, blank=True)
    catalogue_values = models.ManyToManyField(CatalogueValue, blank=True)
    catalogue_employments = models.ManyToManyField(CatalogueEmployment, blank=True)
    catalogue_benefits = models.ManyToManyField(CatalogueBenefit, blank=True)
    catalogue_competences = models.ManyToManyField(CatalogueCompetence, blank=True)
    catalogue_locations = models.ManyToManyField(CatalogueLocation, blank=True)
    catalogue_cities = models.TextField(blank=True, null=True, max_length=400)
    catalogue_average_age = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Average age of employees"
    )
    catalogue_founded = models.PositiveIntegerField(blank=True, null=True)
    fair_location = models.ForeignKey(
        Location, blank=True, null=True, on_delete=models.SET_NULL
    )
    map_coordinates = JSONField(blank=True, null=True)
    vyer_position = models.CharField(blank=True, null=True, max_length=255)
    flyer = models.FileField(
        upload_to="exhibitors/flyers/%Y%m%d/", default=None, blank=True, null=True
    )

    deadline_complete_registration = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="Deviating deadline for complete registration",
    )

    placement_wishes = [
        (None, "No preference"),
        ("MIXED", "Mixed with companies from other industries"),
        ("SIMILAR", "Next to similar companies"),
    ]

    placement_wish = models.CharField(
        choices=placement_wishes, blank=True, null=True, max_length=255
    )
    placement_comment = models.TextField(
        blank=True,
        null=True,
        verbose_name="Additional wishes regarding placement at the fair",
    )

    transport_information_read = models.BooleanField(
        null=False,
        default=False,
    )

    transport_to_statuses = [
        ("NOT_BOOKED", "Not booked"),
        ("BOOKED", "Booked"),
        ("ARKAD", "Transported by Arkad"),
        ("NOT_APPLICABLE", "Not applicable"),
        ("EXCEPTION", "Exception"),
        ("IN_CONTACT", "In contact"),
        ("IN_CONTACT_ARMADA", "In contact by Armada"),
        ("STURE", "Sture"),
        ("BY_HAND", "Carried by hand"),
    ]

    transport_to = models.CharField(
        choices=transport_to_statuses,
        null=False,
        blank=False,
        default="NOT_BOOKED",
        max_length=30,
    )

    transport_from_statuses = [
        ("NOT_BOOKED", "Not booked"),
        ("BOOKED", "Booked"),
        ("NOT_APPLICABLE", "Not applicable"),
        ("EXCEPTION", "Exception"),
        ("IN_CONTACT", "In contact"),
        ("STURE", "Sture"),
        ("BY_HAND", "Carried by hand"),
    ]

    transport_from = models.CharField(
        choices=transport_from_statuses,
        null=False,
        blank=False,
        default="NOT_BOOKED",
        max_length=30,
    )
    transport_comment = models.TextField(blank=True, null=True)

    @property
    def count_lunch_tickets(self):
        count_ordered = 0

        for order in Order.objects.filter(
            purchasing_company=self.company, product=self.fair.product_lunch_ticket
        ):

orders/views.py
from fair.models import Fair
from .models import Product
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import PermissionDenied
from fair.models import Fair
from django.contrib.auth.decorators import permission_required

templates/exhibitors/booth_exhibitor_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block nav-exhibitors %}
	<li role="presentation" class="active"><a href="{% url 'exhibitors' fair.year %}">Exhibitors</a></li>
{% endblock %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="{% url 'exhibitors' fair.year %}">Exhibitors</a></li>
		<li><a href="{% url 'booths' fair.year %}">Booths</a></li>
		<li><a href="{% url 'booth' fair.year booth.pk %}">{{ booth.name }}</a></li>
		<li class="active">{% if eib %} {{ eib.exhibitor.company.name }} {% else %} Assign exhibitor {% endif %}</li>
	</ol>
	
	<h1>{% if eib %} {{ eib.exhibitor.company.name }} in booth {{ booth.name }} {% else %} Assign exhibitor to booth {{ booth.name }} {% endif %}</h1>
	
	<form method="post">
		{% csrf_token %}
		{{ form | crispy }}
		<button class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Save</button>
	</form>
{% endblock %}

templates/exhibitors/booth_placement.html
{% extends "base.html" %}
{% load render_bundle from webpack_loader %}
{% block nav-exhibitors %}
  <li role="presentation" class="active"><a href="{% url 'exhibitors' fair.year %}">Exhibitors</a></li>
{% endblock %}
{% block content %}
  <style>
    html {
      font-size: 16px;
    }
  </style>
  <div id="react"></div>
  <script>
    window.reactProps = {{ react_props|safe }};
  </script>
{% endblock %}
{% block scripts %}
  {% render_bundle 'booth_placement' %}
{% endblock scripts %}

templates/exhibitors/exhibitor.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load humanize %}

{% block nav-exhibitors %}<li role="presentation" class="active"><a href="{% url 'exhibitors' fair.year %}">Exhibitors</a></li>{% endblock %}

{% block content %}
	<ol class="breadcrumb">
		<li><a href="{% url 'exhibitors' fair.year %}">Exhibitors</a></li>
		<li class="active">{{ exhibitor.company }}</li>
	</ol>
	
	<h1>{{ exhibitor.company }}</h1>
	
	<p>
		{% if perms.exhibitors.modify_transport %}<a href="{% url 'exhibitor_transport' fair.year exhibitor.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Transport</a>{% endif %}
		{% if perms.exhibitors.modify_contact_persons %}<a href="{% url 'exhibitor_contact_persons' fair.year exhibitor.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Contact persons</a>{% endif %}
		{% if perms.exhibitors.modify_check_in %}<a href="{% url 'exhibitor_check_in' fair.year exhibitor.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Check in</a>{% endif %}
		{% if perms.exhibitors.modify_details %}<a href="{% url 'exhibitor_details' fair.year exhibitor.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Details</a>{% endif %}
		{% if perms.companies.base %}<a href="{% url 'companies_view' fair.year exhibitor.company.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Company</a>{% endif %}
		{% if perms.exhibitors.modify_coordinates %}<a href="{% url 'exhibitor_coordinates' fair.year exhibitor.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Coordinates</a>{% endif %}
		{% if perms.exhibitors.modify_fair_location %}<a href="{% url 'exhibitor_fair_location' fair.year exhibitor.pk %}" class="btn btn-default"><span class="glyphicon glyphicon-th"></span> Fair Location</a>{% endif %}
		<a href="{% url 'anmalan:registration' exhibitor.company.pk %}" class="btn btn-default pull-right"><span class="glyphicon glyphicon-th"></span> Go to registration</a>
	</p>
	
	<div class="row">
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Responsibilities within {{ fair }}</h3>
				</div>
				
				<div class="panel-body">
					{% if contact_persons %}
						{% for contact_person in contact_persons %}
							<p>
								<a href="{% url 'people:profile' fair.year contact_person.user.profile.pk %}">{{ contact_person.user }}</a>
								{% if contact_person.role %}<br />{{ contact_person.role }}{% endif %}
							</p>
						{% endfor %}
					{% else %}
						<p>No responsibilities specified.</p>
					{% endif %}
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Deadlines</h3>
				</div>
				
				<div class="panel-body">
					<ul class="list-unstyled">
						<li><span style="font-weight: 700;">Complete registration:</span> {{ deadline_complete_registration }}</li>
					</ul>
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Fair location</h3>
				</div>
				
				<div class="panel-body">
					{% if booths %}
						<ul class="list-unstyled">
							<span style="font-weight: 700;">Booths:</span>
							{% for booth in booths %}
								<li><a href="//maps.armada.nu/?location={{ booth.location.pk }}&booth={{ booth.pk }}" target="_blank">{% if booth.location.parent %}{{ booth.location.parent.name }} – {% endif %} {{ booth.location.name }} – {{ booth.name }}</a></li>
							{% endfor %}
						</ul>
					{% else %}
						<p><span style="font-weight: 700;">Booths:</span> No booth(s) assigned.</p>
					{% endif %}
					{%if fair_location %}
						<p><span style="font-weight: 700;">Location:</span> {{fair_location}}</p>
					{% else %}
					<p><span style="font-weight: 700;">Location:</span> No location specified.</p>
					{% endif %}
					{% if fair_location_special %}
						<p><span style="font-weight: 700;">Special location:</span> {{fair_location_special}}</p>
					{% else %}
						<p><span style="font-weight: 700;">Special location:</span> No special location specified.</p>
					{%endif%}
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Transport details</h3>
				</div>
				
				<div class="panel-body">
					<ul class="list-unstyled">
						<li><span style="font-weight: 700;">To the fair:</span> {{ exhibitor.get_transport_to_display }}</li>
						<li><span style="font-weight: 700;">From the fair:</span> {{ exhibitor.get_transport_from_display }}</li>
					</ul>
					
					{% if exhibitor.transport_comment %}<p>{{ exhibitor.transport_comment | linebreaks }}</p>{% endif %}
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Check in</h3>
				</div>
				
				<div class="panel-body">
					{% if exhibitor.check_in_timestamp %}
						<p class="text-success">Checked in on {{ exhibitor.check_in_timestamp }} by <a href="{% url 'people:profile' fair.year exhibitor.check_in_user.profile.pk %}">{{ exhibitor.check_in_user }}</a>.</p>
						
						{% if exhibitor.check_in_comment %}<p>{{ exhibitor.check_in_comment | linebreaks }}</p>{% endif %}
					{% else %}
						<p>Not checked in.</p>
					{% endif %}
				</div>
			</div>
			
			{% for contact in contacts %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">{% if contact.preferred_language %}{{ contact.preferred_language.short }} {% endif %}{{ contact }}</h2>
						{% if contact.title %}{{ contact.title }}{% endif %}
					</div>
					
					<div class="panel-body">
						<ul class="list-unstyled">
							{% if contact.user %}
								<li><strong>Username:</strong> {{ contact.user.username }}</li>
								<li><strong>Registered:</strong> {{ contact.user.date_joined }}</li>
								<li><strong>Last login:</strong> {{ contact.user.last_login }}</li>
							{% endif %}
							
							<li><strong>E-mail address:</strong> <a href="mailto:{{ contact.email_address }}">{{ contact.email_address }}</a></li>
							{% if contact.mobile_phone_number %}<li><strong>Mobile phone number:</strong> <a href="tel:{{ contact.mobile_phone_number }}">{{ contact.mobile_phone_number }}</a></li>{% endif %}
							{% if contact.work_phone_number %}<li><strong>Work phone number:</strong> <a href="tel:{{ contact.work_phone_number }}">{{ contact.work_phone_number }}</a></li>{% endif %}
						</ul>
					</div>
				</div>
			{% endfor %}
		</div>
		
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Orders</h2>
				</div>
				
				<div class="panel-body">
					{% if orders %}
						<table class="table">
							<thead>
								<tr>
									<th>Product</th>
									<th style="text-align: right;">Quantity</th>
									<th style="text-align: right;">Unit price</th>
								</tr>
							</thead>
							
							{% for order in orders %}
								<tr>
									<td>
										{{ order.name }}
										
										{% if order.comment %}
											<br /><span style="font-style: italic;">{{ order.comment }}</span>
										{% endif %}

										{% if order.stock_when_bought <= 0 %}
											<br /><span style="font-style: italic; color: red;">
												Note: this product was ordered without being in stock.
											</span>
										{% endif %}
									</td>
									<td style="text-align: right;">{{ order.quantity }}</td>
									<td style="text-align: right;">{{ order.unit_price | intcomma }}</td>
								</tr>
							{% endfor %}
						</table>

						<a href="{% url 'send_order_summaries' fair.year %}?id={{ exhibitor.company.pk }}" class="btn btn-primary pull-right"onclick="return confirm('Press OK to send out e-mail messages with confirmations.')">Send order confirmation</a>
					{% else %}
						<p>The company has no orders for {{ fair }}.</p>
					{% endif %}
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Lunch tickets</h2>
				</div>
				
				<div class="panel-body">
					<ul class="list-unstyled">
						<li><strong>Ordered lunch tickets:</strong> {{ lunch_tickets_count_ordered }}</li>
						<li><strong>Created lunch tickets:</strong> {{ lunch_tickets_count_created }}</li>
					</ul>
					
					{% for lunch_tickets_day in lunch_tickets_days %}
						{% if lunch_tickets_day.lunch_tickets %}
							<h3>{{ lunch_tickets_day.date }}</h3>
							
							<table class="table">
								<thead>
									<tr>
										<th style="width: 40%;">E-mail address</th>
										<th>Dietary restrictions</th>
									</tr>
								</thead>
								
								{% for lunch_ticket in lunch_tickets_day.lunch_tickets %}
									<tr>
										<td>
											{{ lunch_ticket.email_address }}
											{% if lunch_ticket.comment %}<br /><span style="font-style: italic;">{{ lunch_ticket.comment }}</span>{% endif %}
										</td>
										<td>{{ lunch_ticket.dietary_restrictions.all | join:', ' }}</td>
									</tr>
								{% endfor %}
							</table>
						{% endif %}
					{% endfor %}
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Banquet tickets</h2>
				</div>
				
				<div class="panel-body">
					<ul class="list-unstyled">
						<li><strong>Ordered banquet tickets:</strong> {{ banquet_tickets_count_ordered }}</li>
						<li><strong>Created banquet tickets:</strong> {{ banquet_tickets_count_created }}</li>
					</ul>
					
					{% for banquet in banquets %}
						{% if banquet.banquet_tickets %}
							<h3>{{ banquet.banquet.name }}</h3>
							
							<table class="table">
								<thead>
									<tr>
										<th style="width: 40%;">Name</th>
										<th style="width: 30%;">E-mail address</th>
										<th>Phone number</th>
									</tr>
								</thead>
								
								{% for banquet_ticket in banquet.banquet_tickets %}
									<tr>
										<td>{{ banquet_ticket.name }}</td>
										<td>{{ banquet_ticket.email_address }}</td>
										<td>{{ banquet_ticket.phone_number }}</td>
									</tr>
								{% endfor %}
							</table>
						{% endif %}
					{% endfor %}
				</div>
			</div>
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h2 class="panel-title">Write comment</h2>
				</div>
				
				<div class="panel-body">
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{{ form_comment | crispy }}
						<button class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Save comment</button>
					</form>
				</div>
			</div>
			
			{% for comment in comments %}
				<div class="panel panel-info">
					<div class="panel-heading">
						{% if comment.user == user %}
							<div class="pull-right">
								<a onclick="confirm('Do you want to remove the comment?');" href="{% url 'exhibitor_comment_remove' fair.year exhibitor.pk comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
								<a href="{% url 'exhibitor_comment_edit' fair.year exhibitor.pk comment.pk %}"><span class="glyphicon glyphicon-edit"></span></a>
							</div>
						{% endif %}
						
						<h2 class="panel-title">{{ comment.user }} at {{ comment.timestamp }}</h2>
						{{ comment.groups.all | join:", " }}
					</div>
					
					<div class="panel-body">
						<p>{{ comment.comment | linebreaks }}</p>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}