ais/common/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from ais.common import settings
from django.conf.urls.static import static
from fair.views import login_redirect
from testpage.views import testpage
from exhibitors.views import UserAutocomplete
from magic_link import urls as magic_link_urls

urlpatterns = [
    url(r"^accounts/", include("accounts.urls")),
    url(r"^admin/", admin.site.urls),
    url(r"^companies/", include("companies.urls")),
    url(r"^register/", include("register.urls")),
    url(r"^api/", include("api.urls")),
    url(r"^banquet/", include("banquet.urls")),
    url(r"^$", login_redirect),
    url(r"^fairs/", include("urls.urls")),
    url(r"^journal/", include("journal.urls")),
    url(r"^banquet/", include("banquet.urls_external")),
    url(r"^unirel/", include("unirel.urls_external")),
    url(r"^", include("fair.urls_external")),
    url(r"^testpage/", include("testpage.urls")),
    url(r"^payments/", include("payments.urls")),
    url(r"^hijack/", include("hijack.urls")),
    url(r"^magic_link/", include(magic_link_urls)),
    url(
        r"^user-autocomplete/$",
        UserAutocomplete.as_view(),
        name="user-autocomplete",
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_title = "AIS administration"
admin.site.site_header = "AIS administration"
admin.site.index_title = "AIS administration"

ais/local/urls.py
from ais.common.urls import *
from django.conf.urls import include, url
from kth_login import views as kth_login_views

urlpatterns += [
    url(r"^login/", kth_login_views.kth_login, name="login"),
    url(r"^oidc/kth/callback$", kth_login_views.authorize, name="authorize"),
]

api/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r"^$", views.root),
    url(r"^events/", include("events.api_urls")),
    url(r"^exhibitors/", include("exhibitors.api_urls")),
    url(r"^banquet/", include("banquet.api_urls")),
    url(r"^fair/", include("fair.api_urls")),
    url(r"^registration/", include("register.api_urls")),
    url(r"^accounting/", include("accounting.api_urls")),
    url(r"^catalogueselections/", views.catalogueselections),
    url(r"^news/", views.news),
    url(r"^organization/v2", views.organization_v2),
    url(r"^organization/", views.organization),
    url(r"^create_magic_link/", views.create_magic_link, name="create_magic_link"),
    url(r"^partners/", views.partners),
    url(r"^questions/?$", views.questions),
    url(r"^recruitment/$", views.recruitment),
    url(r"^recruitment_data/$", views.recruitment_data),
    url(r"^dates/$", views.dates),
    url(r"^student_profile$", views.student_profile),
    url(r"^matching/$", views.matching),
    url(r"^matching/choices$", views.matching_choices),
    url(r"^companies", views.companies),
]

banquet/urls.py
from django.conf.urls import url

from banquet import views
from banquet.views import ParticipantsListView, SendInviteCreateView, export_invitations

urlpatterns = [
    url(r"^$", views.dashboard, name="banquet_dashboard"),
    url(
        r"^invitation/(?P<token>[0-9A-Fa-f-]+)$",
        views.invitation,
        name="banquet_invitation",
    ),
    url(
        r"^invitation/(?P<token>[0-9A-Fa-f-]+)/no$",
        views.invitation_no,
        name="banquet_invitation_no",
    ),
    url(
        r"^invitation/(?P<token>[0-9A-Fa-f-]+)/maybe$",
        views.invitation_maybe,
        name="banquet_invitation_maybe",
    ),
    url(r"^(?P<banquet_pk>[0-9]+)$", views.manage, name="banquet_manage"),
    url(r"^(?P<banquet_pk>[0-9]+)/map$", views.manage_map, name="banquet_manage_map"),
    url(
        r"^(?P<banquet_pk>[0-9]+)/invitations$",
        views.manage_invitations,
        name="banquet_manage_invitations",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/invitations/(?P<invitation_pk>[0-9]+)$",
        views.manage_invitation,
        name="banquet_manage_invitation",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/invitations/(?P<invitation_pk>[0-9]+)/edit$",
        views.manage_invitation_form,
        name="banquet_manage_invitation_edit",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/invitations/new$",
        views.manage_invitation_form,
        name="banquet_manage_invitation_new",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/invitations/import$",
        views.manage_import_invitations,
        name="banquet_import_invitations",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/participants$",
        views.manage_participants,
        name="banquet_manage_participants",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/participants/exportafterparty$",
        views.export_afterparty,
        name="banquet_export_afterparty",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/participants/export$",
        views.export_participants,
        name="banquet_export_participants",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/participants/(?P<participant_pk>[0-9]+)$",
        views.manage_participant,
        name="banquet_manage_participant",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/participants/(?P<participant_pk>[0-9]+)/edit$",
        views.manage_participant_form,
        name="banquet_manage_participant_edit",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/participants/(?P<participant_pk>[0-9]+)/remove$",
        views.manage_participant_remove,
        name="banquet_manage_participant_remove",
    ),
    url(
        r"^(?P<banquet_pk>[0-9]+)/invitations/(?P<invitation_pk>[0-9]+)/mail_sent$",
        views.send_invitation_button,
        name="banquet_send_invitation_button",
    ),
    url(r"^participants$", ParticipantsListView.as_view(), name="participant_list"),
    url(r"^send$", SendInviteCreateView.as_view(), name="send_invite"),
    url(r"^export$", export_invitations, name="export_invitations"),
    url(
        r"^scan_tickets/(?P<banquet_pk>[0-9]+)$",
        views.scan_tickets,
        name="scan_tickets",
    ),
]

events/urls.py
from django.conf.urls import url

from events import views

app_name = "events"

urlpatterns = [
    url(r"^$", views.event_list, name="event_list"),
    url(r"^new$", views.event_new, name="event_new"),
    url(r"^(?P<pk>\d+)$", views.event_edit, name="event_edit"),
    url(r"^(?P<event_pk>\d+)/teams$", views.team_new, name="team_new"),
    url(r"^(?P<event_pk>\d+)/check_in$", views.check_in, name="check_in"),
    url(
        r"^(?P<event_pk>\d+)/teams/(?P<team_pk>\d+)$", views.team_edit, name="team_edit"
    ),
    url(r"^(?P<event_pk>\d+)/signup$", views.event_signup, name="event_signup"),
]

people/urls.py
from django.conf.urls import url
from . import views

app_name = "people"

urlpatterns = [
    url(r"^$", views.list, name="list"),
    url(r"^edit$", views.edit, name="edit"),
    url(r"^(?P<pk>\d+)$", views.profile, name="profile"),
    url(r"^profile_delete/(?P<pk>\d+)$", views.profile_delete, name="profile_delete"),
]

events/models.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string

from accounting.models import Product
from fair.models import Fair
from lib.image import UploadToDirUUID
from people.models import Profile


class Event(models.Model):
    fair = models.ForeignKey(Fair, on_delete=models.CASCADE)
    name = models.CharField(max_length=75, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    date_start = models.DateTimeField()
    date_end = models.DateTimeField()
    location = models.CharField(max_length=75, blank=True, null=True)
    food = models.CharField(max_length=75, blank=True, null=True)
    signup_cr = models.BooleanField(
        blank=False, null=False, verbose_name="Let company representatives sign up"
    )
    signup_s = models.BooleanField(
        blank=False, null=False, verbose_name="Let students sign up"
    )
    open_for_signup = models.BooleanField(
        blank=False, null=False, verbose_name="Event is currently open for sign up"
    )
    company_product = models.ForeignKey(
        Product,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name="Product to link the event with",
    )
    teams_create_cr = models.BooleanField(
        blank=False, null=False, verbose_name="Let company representatives create teams"
    )
    teams_create_s = models.BooleanField(
        blank=False, null=False, verbose_name="Let students create teams"
    )
    teams_participate_cr = models.BooleanField(
        blank=False,
        null=False,
        verbose_name="Let company representatives join or leave teams",
    )
    teams_participate_s = models.BooleanField(
        blank=False, null=False, verbose_name="Let students join or leave teams"
    )
    teams_default_max_capacity = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Default max number of team members"
    )  # None => no limit
    fee_s = models.PositiveIntegerField(
        default=0, blank=False, null=False, verbose_name="Sign-up fee for students"
    )
    published = models.BooleanField(
        blank=False, null=False, verbose_name="The event is published on the website"
    )
    requires_invitation = models.BooleanField(
        blank=False,
        null=False,
        verbose_name="Participants need an invitation to sign up",
    )
    contact_person = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.CASCADE
    )
    external_event_link = models.CharField(max_length=255, blank=True, null=True)
    picture = models.ImageField(
        upload_to=UploadToDirUUID("events", "pictures"), blank=True, null=True
    )

    class Meta:
        ordering = ["date_start", "name"]

    def __str__(self):
        return self.name

    @property
    def is_future(self):
        return timezone.now() < self.date_start

    @property
    def is_past(self):
        return timezone.now() > self.date_end


class Invitation(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    invitee = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    fee = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Fee to participate"
    )  # None => default student fee (Event.fee_s)
    date = models.DateTimeField(auto_now_add=True)


class Team(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=75, blank=False, null=False)
    max_capacity = models.PositiveIntegerField(
        blank=True, null=True, verbose_name="Max number of team members"
    )  # None => no limit
    allow_join_cr = models.BooleanField(
        default=True,
        blank=False,
        null=False,
        verbose_name="Allow company representatives to join the team",
    )
    allow_join_s = models.BooleanField(
        default=True,
        blank=False,
        null=False,
        verbose_name="Allow students to join the team",
    )

    def is_full(self):
        return self.number_of_members() >= self.max_capacity

    def number_of_members(self):
        return self.teammember_set.count()

    def __str__(self):
        return self.name


def get_random_32_length_string():
    return get_random_string(32)


class Participant(models.Model):
    event = models.ForeignKey(Event, blank=False, null=True, on_delete=models.CASCADE)
    name = models.CharField(
        blank=True, null=True, max_length=255
    )  # None for students, required for company representatives
    email_address = models.CharField(
        blank=True, null=True, max_length=255
    )  # None for students, required for company representatives
    phone_number = models.CharField(
        blank=True, null=True, max_length=255
    )  # None for students, required for company representatives
    user_cr = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.CASCADE, related_name="user_cr"
    )  # either this one...
    user_s = models.ForeignKey(
        User, blank=True, null=True, on_delete=models.CASCADE, related_name="user_s"
    )  # ...or this one
    stripe_charge_id = models.CharField(
        max_length=50, blank=True, null=True
    )  # None for company representatives, filled in if the
    # student has payed using Stripe
    fee_payed_s = models.BooleanField(default=False)
    attended = models.NullBooleanField(
        blank=True, null=True, verbose_name="The participant showed up to the event"
    )
    signup_complete = models.BooleanField(
        blank=False,
        null=False,
        default=False,
        verbose_name="The participant has completed signup",
    )
    check_in_token = models.CharField(
        max_length=32, unique=True, default=get_random_32_length_string
    )
    timestamp = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    # Name, email and phone number can be stored either in this model or in the user model depending on if this is a student or not,
    # so we define these help functions to get them easier

    def assigned_name(self):
        if self.user_s:
            return self.user_s.get_full_name()
        else:
            return self.name

    def assigned_email(self):
        if self.user_s:
            return self.user_s.email
        else:
            return self.email_address

    def assigned_phone_number(self):
        if self.user_s:
            return Profile.objects.get(user=self.user_s).phone_number
        else:
            return self.phone_number

    def has_checked_in(self):
        return self.participantcheckin_set.count() > 0

    def team(self):
        return (
            self.teammember_set.first().team
            if self.teammember_set.first() is not None
            else None
        )

    def __str__(self):
        if self.user_s:
            return self.user_s.get_full_name()
        elif self.user_cr:
            return self.user_cr.get_full_name()
        else:
            return self.name


class ParticipantCheckIn(models.Model):
    timestamp = models.DateTimeField(
        null=True,
        auto_now_add=True,
        verbose_name="When the participant checked in at the event",
    )
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)


class TeamMember(models.Model):
    team = models.ForeignKey(Team, blank=False, null=False, on_delete=models.CASCADE)
    participant = models.ForeignKey(
        Participant, blank=False, null=False, on_delete=models.CASCADE
    )
    leader = models.BooleanField(blank=False, null=False, default=False)

    def __str__(self):
        return self.participant.__str__() + self.team.__str__()


class TeamInvitation(models.Model):
    team = models.ForeignKey(Team, blank=False, null=False, on_delete=models.CASCADE)
    invitee = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


class SignupQuestion(models.Model):
    QUESTION_TYPES = (
        ("text_field", "Short Text"),
        ("text_area", "Long Text"),
        ("single_choice", "Single Choice"),
        ("multiple_choice", "Multiple Choice"),
        ("student_program", "Student Program"),
        ("file_upload", "File Upload"),
    )

    class Meta:
        ordering = ["pk"]

    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    type = models.CharField(
        blank=False, null=False, choices=QUESTION_TYPES, max_length=20
    )
    question = models.TextField(blank=False, null=False)
    required = models.BooleanField(blank=False, null=False)
    options = ArrayField(models.TextField(blank=False, null=False), default=list)


class SignupQuestionAnswerFile(models.Model):
    file = models.FileField(upload_to=UploadToDirUUID("events", "files"))


class SignupQuestionAnswer(models.Model):
    signup_question = models.ForeignKey(
        SignupQuestion, blank=False, null=False, on_delete=models.CASCADE
    )
    participant = models.ForeignKey(
        Participant, blank=False, null=False, on_delete=models.CASCADE
    )
    answer = models.TextField()  # Used for 'text_field' and 'text_area'
    file = models.ForeignKey(
        SignupQuestionAnswerFile,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ["signup_question__pk"]

templates/events/check_in.html
{% load render_bundle from webpack_loader %}
<title>THS Armada</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"/>
<meta name="theme-color" content="#01d690">

<script>
  window.reactProps = {{ react_props|safe }};
</script>
<div id="react"></div>

{% render_bundle 'check_in' %}

templates/events/emails.html
<h1>E-mail addresses</h1>
<p>Make sure to use blind carbon copies (BCC) when sending e-mail messages to the people below.</p>
<p>The e-mails are sorted on sign-up time with the first person to sign up first in the e-mail list.</p>

<style type="text/css">
	textarea
	{
		height: 200px;
		width: 100%;
		box-sizing: border-box;
		font-size: 12pt;
	}
</style>

<textarea>
{% for participant in participants|dictsort:"timestamp" %}{{ participant.assigned_name }} <{{ participant.assigned_email }}> {% if not forloop.last %}, {% endif %}{% endfor %}
</textarea>

templates/events/event_edit.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block nav-events %}<li role="presentation" class="active"><a href="{% url 'events:event_list' fair.year %}">Events</a></li>{% endblock %}

{% block content %}
  <h1>{{ event.name }}</h1>
  <a href="{% url 'events:check_in' fair.year event.id %}" class="btn btn-default btn-checkin">Check in</a>
  <ul class="nav nav-tabs nav-tabs-margin" role="tablist">
    <li role="presentation" class="active"><a href="#details" aria-controls="details" role="tab"
                                              data-toggle="tab">Details</a>
    </li>
    <li role="presentation"><a href="#participants" aria-controls="participants" role="tab" data-toggle="tab">Participants
      ({{ event.participant_set.count }})</a>
    </li>
    <li role="presentation"><a href="#teams" aria-controls="teams" role="tab" data-toggle="tab">Teams
      ({{ event.team_set.count }})</a>
    </li>

    <li role="presentation"><a href="#emails" aria-controls="emails" role="tab" data-toggle="tab">E-mails</a></li>

  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="details">
      {% include 'events/event_form.html' with form=form questions=questions question_types=question_types %}
    </div>
    <div role="tabpanel" class="tab-pane" id="participants">
      {% include 'events/participant_list.html' with participants=participants questions=questions %}
    </div>
    <div role="tabpanel" class="tab-pane" id="teams">
      <div>
        <a href="{% url 'events:team_new' fair.year event.id %}" class="btn btn-default">New team</a>
      </div>
      {% include 'events/team_list.html' with teams=event.team_set.all event=event %}
    </div>
    <div role="tabpanel" class="tab-pane" id="emails">
        {% include 'events/emails.html' with participants=participants %}
    </div>
  </div>
{% endblock %}

{% block scripts %}
	<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
	<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet" />
	
	<script>
  // Keep track of tab navigation by updating the url hash
  $(".nav-tabs").find("li a").each(function (key, val) {
    // If hash exists, navigate to tab
    if (window.location.hash == $(val).attr('href')) {
      $(val).trigger('click');
    }
    // Update hash when changing tab
    $(val).off('click').on('click', function (e) {
      e.preventDefault();
      window.location.hash = $(this).attr('href');
    });
  });

  $(function () {
    $('#participants_table').DataTable({ 'paging': false });
  })

  // update participants information and reload page
  $('#update_participants_button').off('click').on('click', function (e) {
    e.preventDefault();

    var $this = $(this);
    $this.button('loading'); // Change button to loading state
    $('#participants_table').addClass("disabled");

    $.ajax({
      type: 'GET',
      url: $this.data('url'),
      success: function () {
        location.reload()
      },
      error: function (request, textStatus, error) {
        console.log('cannot fetch participants details.');
      },
      complete: function () {
        $('#participants_table').removeClass("disabled");
        $this.button('reset');
      }
    });
  });
</script>
{% endblock %}

templates/events/event_form.html
{% load render_bundle from webpack_loader %}
{% load crispy_forms_tags %}

<form id="event-form" method="post">
  {% csrf_token %}
  {{ form | crispy }}
</form>
<script>
  window.reactProps = {{ react_props|safe }};
</script>
<div id="react">
</div>

{% render_bundle 'event_form' %}

templates/events/event_list.html
{% extends "base.html" %}

{% block nav-events %}
  <li role="presentation" class="active"><a href="{% url 'events:event_list' fair.year %}">Events</a></li>
{% endblock %}

{% block content %}
  <h1>Events</h1>
  <div>
    <a href="{% url 'events:event_new' fair.year %}" class="btn btn-default">New event</a>
  </div>

  {% include 'events/event_table.html' with events=events %}

{% endblock %}

templates/events/event_new.html
{% extends "base.html" %}
{% block content %}
  <h1>New Event</h1>
  {% include 'events/event_form.html' with form=form %}
{% endblock %}

templates/events/event_not_published.html
{% load render_bundle from webpack_loader %}
<title>THS Armada - {{ event.name }}</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"/>
<meta name="theme-color" content="#01d690">

<div>This event is not yet published</div>

templates/events/event_signup.html
{% load render_bundle from webpack_loader %}
<title>THS Armada - {{ event.name }}</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"/>
<meta name="theme-color" content="#01d690">

<script>
  window.reactProps = {{ react_props|safe }};
</script>
<div id="react"></div>

<script src="https://js.stripe.com/v3/"></script>
<script src="https://checkout.stripe.com/checkout.js"></script>

{% render_bundle 'signup' %}

templates/events/event_table.html
{% if events %}
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Date</th>
      {% if perms.events.base %}
        <th class="text-center">Participants</th> {% endif %}
      <th>Signup</th>
      {% if perms.events.base %}
        <th>Published</th> {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for event in events %}
      <tr>
        <td>
          {% if perms.events.change_event %}
            <a href="{% url 'events:event_edit' fair.year event.id %}">{{ event.name }}</a>
          {% elif event.open_for_signup %}
            <a href="{% url 'events:event_signup' fair.year event.id %}">{{ event.name }}</a>
          {% else %}
            {{ event.name }}
          {% endif %}
        </td>
        <td>{{ event.date_start|date:"d M H:i" }} - {{ event.date_end|date:"d M H:i" }}</td>
        {% if perms.events.base %}
          <td class="text-center">{{ event.num_participants }}</td> {% endif %}
        <td>
          {% if event.open_for_signup %}
            <span class="label label-success">Open</span>
          {% else %}
            <span class="label label-default">Closed</span>
          {% endif %}
        </td>
        {% if perms.events.base %}
          <td>
            {% if event.published %}
              <span class="label label-success">Yes</span>
            {% else %}
              <span class="label label-default">No</span>
            {% endif %}
          </td>
        {% endif %}
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="text-center">No events... yet!</p>
{% endif %}

templates/events/new_event.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>New Event</h1>
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <input class="btn btn-primary" type="submit" value="Submit"/>
  </form>
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    $(function () {
      $('#div_id_date_start').datetimepicker();
    });
  </script>
{% endblock %}

templates/events/participant_list.html
<div>
	<p style="margin-top: 16px">Synchronize participants' details with their KTH accounts. Only participants with 'kth_synchronize' enabled in their profiles will be updated.</p>
	<button type="button" class="btn btn-default btn-updateparticipants" id="update_participants_button"
		data-loading-text="<span class='glyphicon glyphicon-refresh glyphicon-refresh-animate'></span> Updating participants"
		data-url="{% url 'events_api:fetch_participants_details' event.id %}">
		Update participants
	</button>
</div>

<div class="table-responsive">
	<table class="table" id="participants_table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Sign-up</th>
				<th>Team</th>
				<th style="white-space: nowrap;">E-mail address</th>
				<th style="white-space: nowrap;">Phone number</th>
				<th>Type</th>
				{% for question in questions %}
					<th style="white-space: nowrap; text-align: right;">{{ question.question }}</th>
				{% endfor %}
			</tr>
		</thead>
	
		<tbody>
			{% for participant in participants %}
				<tr>
					<td style="white-space: nowrap;">
						{% if participant.user_s %} <a href="{% url 'people:profile' fair.year participant.user_s.pk %}">{{ participant.assigned_name }}</a>
						{% else %}{{ participant.assigned_name }}{% endif %}
					</td>
					<td style="white-space: nowrap;">{% if participant.timestamp %}<span style="display: none;">{{ participant.timestamp|date:"U" }}</span>{{ participant.timestamp }}{% endif %}</td>
					<td>{{ participant.teammember_set.first.team.name }}</td>
					<td><a href="mailto:{{ participant.assigned_email }}">{{ participant.assigned_email }}</a></td>
					<td>{% if participant.assigned_phone_number %}<a href="tel:{{ participant.assigned_phone_number }}">{{ participant.assigned_phone_number }}</a>{% endif %}</td>
					
					<td>
						{% if participant.user_cr %} Company rep.
						{% else %} Student {% endif %}
					</td>
					{% for answer in participant.signupquestionanswer_set.all %}
						<td style="text-align: right;">
							{% if answer.file %}
								<a href="{{ answer.file.file.url }}" target="_blank">
									Download File
								</a>
							{% else %}
								{{ answer.answer }}
							{% endif %}
						</td>
					{% endfor %}
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

templates/events/qr_scanner.html
{% load render_bundle from webpack_loader %}
<title>THS Armada</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"/>
<meta name="theme-color" content="#01d690">

<div id="react"></div>

{% render_bundle 'qr_scanner' %}

templates/events/team_edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <h1>
    {% if team %}
      {{ team.name }}
    {% else %}
      New Team
    {% endif %}
  </h1>
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <input class="btn btn-primary" type="submit" value="Submit"/>
  </form>
{% endblock %}

templates/events/team_list.html
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th class="text-center">No. members</th>
    <th>Open for</th>
  </tr>
  </thead>
  {% for team in teams %}
    <tr>
      <td><a href="{% url 'events:team_edit' fair.year event.id team.id %}">{{ team.name }}</a></td>
      <td class="text-center">{{ team.teammember_set.count }}/{{ team.max_capacity }}</td>
      <td>
        {% if team.allow_join_cr and team.allow_join_s %}
          Mixed
        {% elif team.allow_join_cr %}
          Company reps.
        {% elif team.allow_join_s %}
          Students
        {% else %}
          Closed
        {% endif %}
      </td>
    </tr>
  {% endfor %}
</table>